### ISSUE TITLE
panic: interface conversion: ast.Expr is *ast.IndexExpr, not *ast.Ident

### ISSUE THREAD

**Issue by softwarespot** [karamaru-alpha/copyloopvar#7]
There is an issue with the code below, where it assumes  `value = rangeStmt.Value.(*ast.Ident)` is of type `*ast.Ident` when in my case it's `*ast.IndexExpr,`.

I am very happy to help, as I tried to debug which code was the problem to provide either re-producible code or a MR, but I must be honest, I have never debugged code outside of my own workspace. If you can advise me how to run it locally, then I would be more than willing to help.

```
func checkRangeStmt(pass *analysis.Pass, rangeStmt *ast.RangeStmt) {
	key, ok := rangeStmt.Key.(*ast.Ident)
	if !ok {
		return
	}
	var value *ast.Ident
	if rangeStmt.Value != nil {
		value = rangeStmt.Value.(*ast.Ident)
	}
```

This is a great linter, as I found two places when in all honesty I thought I didn't have any. Great job!

**Comment by SuperSandro2000** [comment]
I've hit the same error through golangci-lint but I couldn't pin down the source code, yet. The trace is

```
ERRO [runner] Panic: copyloopvar: package "datamodel" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident: goroutine 8953 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.57.1/pkg/golinters/goanalysis/runner_action.go:108 +0x277
panic({0x17adfa0?, 0xc0165802a0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/karamaru-alpha/copyloopvar.checkRangeStmt(0xc0165a6000?, 0x1e?)
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/karamaru-alpha/copyloopvar@v1.0.8/copyloopvar.go:55 +0x4b0
github.com/karamaru-alpha/copyloopvar.run.func1({0x1be2858?, 0xc004b05b00?})
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/karamaru-alpha/copyloopvar@v1.0.8/copyloopvar.go:39 +0x65
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc013941128, {0xc00b4d1cb8?, 0x24a7fe0?, 0xc00b4d1cd8?}, 0xc015313ca8)
	/tmp/build/f541ec31/gopath/pkg/mod/golang.org/x/tools@v0.19.0/go/ast/inspector/inspector.go:82 +0x8f
github.com/karamaru-alpha/copyloopvar.run(0xc0165a6000)
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/karamaru-alpha/copyloopvar@v1.0.8/copyloopvar.go:36 +0xa5
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc002f88370)
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.57.1/pkg/golinters/goanalysis/runner_action.go:190 +0xa02
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.57.1/pkg/golinters/goanalysis/runner_action.go:112 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0029bd720, {0x195bbb9, 0xb}, 0xc007581748)
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.57.1/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0x9?)
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.57.1/pkg/golinters/goanalysis/runner_action.go:111 +0x7a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc002f88370)
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.57.1/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa8
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 700
	/tmp/build/f541ec31/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.57.1/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x205 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: copyloopvar: package "datamodel" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident 
ERRO Running error: can't run linter goanalysis_metalinter
goanalysis_metalinter: copyloopvar: package "datamodel" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident 
```

**Comment by SuperSandro2000** [comment]
I found a reproducer. When the for range writes the variable into a struct.

https://github.com/sapcc/limes/blob/7157e4b11a56998bad2c50b1df8724065bd48012/internal/datamodel/apply_computed_project_quota_test.go#L116

**Comment by karamaru-alpha** [comment]
@softwarespot 

Thank you for reporting the bug!!!
I will fix it(ignoring rangeStmt value whoes type is not `*ast.Ident`) within today.

**Comment by softwarespot** [comment]
Thanks for fixing
